[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg", "curl"]

[phases.install]
cmds = [
  "npm install",
  "mkdir -p bin && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux -o bin/yt-dlp && chmod +x bin/yt-dlp"
]

[start]
cmd = "node index.js"
